[package]
name = "media-server"
version = "0.1.0"
authors = ["Benjamin Herman <benjamin@metanomial.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
rocket = "0.5.0-rc.2"
